[package]
name = "memcrs"
version = "0.0.1"
authors = ["Dariusz Ostolski <dariusz.ostolski@gmail.com>"]
edition = "2021"


[lib]
name = "memcrs"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte-unit = "4.0.14"
bytes = "1.1.0"
clap = { version = "3.1.5", features = ["cargo"] }
dashmap = "5.1.0"
failure = { version = "0.1.8" }
failure_derive = { version = "0.1.8" }
futures = "0.3.19"
futures-util = "0.3.19"
log = "0.4.14"
socket2 = { version = "0.4.2", features = ["all"] }
num_cpus = "1.13.0"
num-derive = "0.3.3"
num-traits = "0.2.14"
rand = { version = "0.8.4", features = ["small_rng"] }
serde = "1.0.132"
serde_derive = "1.0.132"
tracing = "0.1.31"
tracing-attributes = "0.1.19"
tracing-log = "0.1.2"
tracing-subscriber = "0.3.9"
# enable kbio
tokio = { path = "/root/project/kbio/tokio", features = ["fs", "io-util", "io-std", "macros", "net", "parking_lot", "rt", "rt-multi-thread", "sync", "time", "kbio"] }
# disable kbio
#tokio = { path = "/root/project/kbio/tokio", features = ["fs", "io-util", "io-std", "macros", "net", "parking_lot", "rt", "rt-multi-thread", "sync", "time",] }
tokio-util = { version = "0.7.0", features = ["full"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { version ="0.3.2", optional = true }
